# Generated by Django 3.1.1 on 2020-09-14 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('maquina', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('componente', models.CharField(max_length=250)),
                ('funcao_perdida', models.CharField(max_length=250)),
                ('inicio_avaria', models.DateTimeField(auto_now_add=True)),
                ('fim_avaria', models.DateTimeField(auto_now_add=True)),
                ('tempo_reparo', models.DurationField()),
                ('oque', models.TextField()),
                ('onde', models.TextField()),
                ('quando', models.TextField()),
                ('quem', models.TextField()),
                ('porque', models.TextField()),
                ('como', models.TextField()),
                ('reincidencia', models.TextField()),
                ('fenomenos', models.TextField()),
                ('componete_pos_intervencao', models.CharField(max_length=100)),
                ('modo_falha', models.CharField(max_length=100)),
                ('operador', models.CharField(max_length=100)),
                ('mantenedor', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=2)),
                ('turno', models.CharField(max_length=5)),
                ('participantes', models.CharField(max_length=200)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
